name: Deploy Project Alpha

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Verify working directory
      run: ls -la
      working-directory: .

    - name: Install dependencies
      run: npm install
      working-directory: ./wwwroot

    - name: Build project
      run: npm run build
      working-directory: ./wwwroot

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./wwwroot/dist